name: kal_gs
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit=11.8
  - pytorch-cuda=11.8  # For old torch versions this is cudatoolkit=11.3, see gsplat's original environment.yaml file
  - plyfile
  - python=3.9
  - pip=22.3.1
  - pytorch=2.0.1
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
